<a href="https://colab.research.google.com/github/miotomita/covid_automation/blob/main/Vdata%E7%94%A8%E3%81%AE%E4%BA%BA%E5%8F%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
!pip install tabula-py
!pip install gspread_pandas
#gspreadのモジュールエラーが出たため（2021/12/30）
!git clone https://github.com/robin900/gspread-dataframe.git
%cd gspread-dataframe
!python setup.py install

Requirement already satisfied: tabula-py in /usr/local/lib/python3.7/dist-packages (2.3.0)
Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.6.0)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.1.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)
Requirement already satisfied: gspread_pandas in /usr/local/lib/python3.7/dist-packages (3.0.2)
Requirement already satisfied: google-auth in /usr/local/lib/python3.7/dist-packages (from gspread_pandas) (1.35.0)
Requirement already satisfied: pandas>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from gspread_pandas) (1.1.5)
Requirement already satisfied: gspread>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from gspread_pandas) (5.1.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from gspread_pandas) (4.4.2)
Requirement already satisfied: google-auth-oauthlib in /usr/local/lib/python3.7/dist-packages (from gspread_pandas) (0.4.6)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread_pandas) (4.2.4)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread_pandas) (57.4.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread_pandas) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread_pandas) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread_pandas) (4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib->gspread_pandas) (1.3.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.20.0->gspread_pandas) (2018.9)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.20.0->gspread_pandas) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.20.0->gspread_pandas) (2.8.2)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth->gspread_pandas) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (3.1.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib->gspread_pandas) (3.0.4)
Cloning into 'gspread-dataframe'...
remote: Enumerating objects: 634, done.
remote: Counting objects: 100% (298/298), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 634 (delta 195), reused 200 (delta 103), pack-reused 336
Receiving objects: 100% (634/634), 143.16 KiB | 9.54 MiB/s, done.
Resolving deltas: 100% (378/378), done.
/content/gspread-dataframe/gspread-dataframe/gspread-dataframe
running install
running bdist_egg
running egg_info
creating gspread_dataframe.egg-info
writing gspread_dataframe.egg-info/PKG-INFO
writing dependency_links to gspread_dataframe.egg-info/dependency_links.txt
writing requirements to gspread_dataframe.egg-info/requires.txt
writing top-level names to gspread_dataframe.egg-info/top_level.txt
writing manifest file 'gspread_dataframe.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'gspread_dataframe.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
copying gspread_dataframe.py -> build/lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib/gspread_dataframe.py -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/gspread_dataframe.py to gspread_dataframe.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gspread_dataframe.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/gspread_dataframe-3.2.2-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gspread_dataframe-3.2.2-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/gspread_dataframe-3.2.2-py3.7.egg
Copying gspread_dataframe-3.2.2-py3.7.egg to /usr/local/lib/python3.7/dist-packages
gspread-dataframe 3.2.2 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/gspread_dataframe-3.2.2-py3.7.egg
Processing dependencies for gspread-dataframe==3.2.2
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for pandas==1.1.5
Best match: pandas 1.1.5
Adding pandas 1.1.5 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for gspread==5.1.1
Best match: gspread 5.1.1
Adding gspread 5.1.1 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for python-dateutil==2.8.2
Best match: python-dateutil 2.8.2
Adding python-dateutil 2.8.2 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Adding numpy 1.19.5 to easy-install.pth file
Installing f2py script to /usr/local/bin
Installing f2py3 script to /usr/local/bin
Installing f2py3.7 script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Searching for pytz==2018.9
Best match: pytz 2018.9
Adding pytz 2018.9 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for google-auth-oauthlib==0.4.6
Best match: google-auth-oauthlib 0.4.6
Adding google-auth-oauthlib 0.4.6 to easy-install.pth file
Installing google-oauthlib-tool script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Searching for google-auth==1.35.0
Best match: google-auth 1.35.0
Adding google-auth 1.35.0 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for requests-oauthlib==1.3.0
Best match: requests-oauthlib 1.3.0
Adding requests-oauthlib 1.3.0 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for pyasn1-modules==0.2.8
Best match: pyasn1-modules 0.2.8
Adding pyasn1-modules 0.2.8 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for cachetools==4.2.4
Best match: cachetools 4.2.4
Adding cachetools 4.2.4 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for setuptools==57.4.0
Best match: setuptools 57.4.0
Adding setuptools 57.4.0 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for rsa==4.8
Best match: rsa 4.8
Adding rsa 4.8 to easy-install.pth file
Installing pyrsa-decrypt script to /usr/local/bin
Installing pyrsa-encrypt script to /usr/local/bin
Installing pyrsa-keygen script to /usr/local/bin
Installing pyrsa-priv2pub script to /usr/local/bin
Installing pyrsa-sign script to /usr/local/bin
Installing pyrsa-verify script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Searching for requests==2.23.0
Best match: requests 2.23.0
Adding requests 2.23.0 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for oauthlib==3.1.1
Best match: oauthlib 3.1.1
Adding oauthlib 3.1.1 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for urllib3==1.24.3
Best match: urllib3 1.24.3
Adding urllib3 1.24.3 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for certifi==2021.10.8
Best match: certifi 2021.10.8
Adding certifi 2021.10.8 to easy-install.pth file

Using /usr/local/lib/python3.7/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.7/dist-packages
Finished processing dependencies for gspread-dataframe==3.2.2

In [128]:
import pandas as pd
import tabula
import re
import numpy as np
from decimal import Decimal, ROUND_HALF_EVEN,ROUND_HALF_UP,ROUND_HALF_DOWN, ROUND_CEILING, ROUND_FLOOR,ROUND_UP, ROUND_DOWN, ROUND_05UP

In [129]:
from google.colab import auth
from oauth2client.client import GoogleCredentials
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe

In [130]:
#認証
auth.authenticate_user()
gc = gspread.authorize(GoogleCredentials.get_application_default())

In [297]:
#日本ワクチンBD
japan_vax = gc.open_by_key('1U2-Kwgr08sC1mP8rwgW8U4NyYuuX2VQYhhG-nS9BtQM')
#日本BD、改定後シート（予定、2021.12末時点）
japan = gc.open_by_key('1sdkJZ-h-k3ywr_bpWDkRae0ExDfSXwG5RdOSzNtcdqk')

In [274]:
pref_names = pd.read_csv('https://raw.githubusercontent.com/miotomita/meta/main/prefecture_names.csv',index_col=0)
pref_code_dic = pref_names.loc[~pref_names.code_pref.isna()].set_index('prefecture_j').code_pref.to_dict()

In [132]:
def round0(x):
    return float(Decimal(str(x)).quantize(Decimal('0'),rounding=ROUND_HALF_UP))

In [133]:
def roundceil(x):
  return float(Decimal(str(x)).quantize(Decimal('0'),rounding=ROUND_CEILING))

In [134]:
def roundfloor(x):
  return float(Decimal(str(x)).quantize(Decimal('0'),rounding=ROUND_FLOOR))

# 年齢階級別人口、住民基本台帳

In [135]:
#【総計】令和3年住民基本台帳年齢階級別人口（市区町村別）
juki_url = 'https://www.soumu.go.jp/main_content/000762465.xlsx'

In [136]:
juki_raw = pd.read_excel(juki_url,header=1)

In [137]:
juki_raw.columns = ['コード','都道府県名','市区町村名','性別'] + juki_raw.columns[4:].to_list()

In [138]:
juki_raw['コード'] = juki_raw['コード'].apply(lambda x:pd.to_numeric(x,errors='ignore'))

# 市区町村データからの積み上げ

In [139]:
#市区町村コード
url = 'https://www.soumu.go.jp/main_content/000730858.xlsx'

In [140]:
codes = pd.read_excel(url,sheet_name='R1.5.1現在の団体')
codes2 = pd.read_excel(url, sheet_name = 'H30.10.1政令指定都市')

In [141]:
#現在の団体（都道府県＋市区町村）
codes = codes.iloc[:,:-2].replace({'合計':'全国','\s':'','\W':'',' ':''}, regex=True)
codes.columns = ['コード','都道府県名','市区町村名']
codes['コード'] = codes['コード'].apply(lambda x: pd.to_numeric(x, errors='coerce'))

In [142]:
#政令市＋サブディビジョン
codes2 = codes2.iloc[:,:-2].replace({'合計':'全国','\s':'','\W':'',' ':''}, regex=True)
codes2.columns = ['コード','都道府県名','市区町村名']
codes2['コード'] = codes2['コード'].apply(lambda x: pd.to_numeric(x, errors='coerce'))

In [143]:
#都道府県
pref_code = codes[codes.市区町村名.isna()].set_index('コード').dropna(how='all',axis=1)
pref_code.head()

      都道府県名
コード
10006   北海道
20001   青森県
30007   岩手県
40002   宮城県
50008   秋田県

In [144]:
#基礎自治体
dist_code = codes[~codes.市区町村名.isna()].set_index('コード')
dist_code

       都道府県名 市区町村名
コード
11002    北海道   札幌市
12025    北海道   函館市
12033    北海道   小樽市
12041    北海道   旭川市
12050    北海道   室蘭市
...      ...   ...
473618   沖縄県  久米島町
473626   沖縄県  八重瀬町
473758   沖縄県  多良間村
473812   沖縄県   竹富町
473821   沖縄県  与那国町

[1747 rows x 2 columns]

In [145]:
#北方領土
kuril = [16951, 16969, 16977, 16985, 16993, 17001]
#東京、島嶼（小笠原などと重複）
isld = [133604]

In [146]:
#政令市
seirei = list(set(codes2.コード)&set(dist_code.index))
#政令市のサブディビジョン
seirei_sub = list(set(codes2.コード) - set(seirei))

In [147]:
#人口データのコードすべて - 北方領土・東京島嶼・政令市のサブ・基礎自治体
dist_na = list(set(juki_raw['コード'].apply(lambda x: pd.to_numeric(x, errors='coerce')).dropna()) - set(kuril + isld + seirei_sub + dist_code.index.to_list()+pref_code.index.to_list()) )

In [148]:
#郡部
gunbu = juki_raw.loc[(juki_raw.コード.isin(dist_na))&(juki_raw.性別=='計')&(juki_raw.市区町村名.apply(lambda x: str(x)[-1]=='郡'))]['コード'].to_list()

In [149]:
#中芸広域連合＝398781
#高知県奈半利町、田野町、安田町、北川村、馬路村が連携しちゅう・・・・
#ここを先に合算しないと、12歳〜人口の全国合算が「１人」少なくなるため注意
chugei = [393029, 393037, 393045, 393053, 393061]
juki_raw.loc[juki_raw.コード.isin(chugei)&(juki_raw.性別=='計')]

         コード 都道府県名    市区町村名 性別    総数  ... 80歳～84歳 85歳～89歳 90歳～94歳 95歳～99歳 100歳以上
5695  393029   高知県  安芸郡奈半利町  計  3119  ...     225     205      94      37      8
5698  393037   高知県   安芸郡田野町  計  2606  ...     187     144      75      31      6
5701  393045   高知県   安芸郡安田町  計  2594  ...     209     167      92      30      1
5704  393053   高知県   安芸郡北川村  計  1247  ...      86     100      41      17      0
5707  393061   高知県   安芸郡馬路村  計   832  ...      63      57      21       7      1

[5 rows x 26 columns]

In [150]:
set(dist_na) - set(gunbu)

set()

住民基本台帳、男女別、市区町村別

In [151]:
#男女別、基礎自治体
juki_mf = juki_raw.loc[(juki_raw.性別.isin(['男','女']))&(~juki_raw.コード.isin(pref_code.index.to_list()+gunbu+kuril+isld+seirei_sub+['-']))].reset_index(drop=True)

In [152]:
juki_mf.iloc[:,4:] = juki_mf.iloc[:,4:].applymap(lambda x: pd.to_numeric(x, errors='coerce'))

In [153]:
juki_mf.columns = [col.replace('～','から') for col in juki_mf.columns]

In [154]:
#ワクチン接種では中芸広域連合（高知）の５町村を合算してから計算する（デジタル庁の説明）
#http://www.chugei-kouiki.jp/
chugei_data = juki_mf.loc[juki_mf.コード.isin(chugei)].groupby(['性別']).sum()
chugei_data['都道府県名'] = '高知県'
chugei_data['市区町村名'] = '中芸広域連合'
chugei_data['コード'] = 398781
chugei_data = chugei_data.reset_index()
chugei_data

  性別     コード 都道府県名   市区町村名  ...  85歳から89歳  90歳から94歳  95歳から99歳  100歳以上
0  女  398781   高知県  中芸広域連合  ...       433       234       101      16
1  男  398781   高知県  中芸広域連合  ...       240        89        21       0

[2 rows x 26 columns]

In [155]:
juki_mf = juki_mf.loc[~juki_mf.コード.isin(chugei)].append(chugei_data).reset_index(drop=True)

In [156]:
#合算する団体数
juki_mf.shape[0]/2

1737.0

In [157]:
juki_mf.tail()

         コード 都道府県名     市区町村名 性別  ... 85歳から89歳 90歳から94歳 95歳から99歳 100歳以上
3469  473812   沖縄県   八重山郡竹富町  女  ...       77       71       26      4
3470  473821   沖縄県  八重山郡与那国町  男  ...       15        3        0      0
3471  473821   沖縄県  八重山郡与那国町  女  ...       31        9        3      2
3472  398781   高知県    中芸広域連合  女  ...      433      234      101     16
3473  398781   高知県    中芸広域連合  男  ...      240       89       21      0

[5 rows x 26 columns]

基礎データの取得はここまでで終わり<br>
12~14歳の計算用にはここまで↑の基礎自治体別・男女別データを使う

In [284]:
#都道府県別
juki_by_pref = juki_mf.fillna(0).groupby('都道府県名').sum().reindex(pref_code['都道府県名'].to_list()).astype(int).drop('コード',axis=1)
juki_by_pref.loc['全国'] = juki_by_pref.sum()
juki_by_pref.insert(1,'全人口_年齢性別判明分',juki_by_pref.loc[:,'0歳から4歳':'100歳以上'].sum(axis=1))

In [285]:
juki_by_pref['numeric'] = juki_by_pref.index.map(pref_code_dic)
juki_by_pref = juki_by_pref.reset_index(drop=False).set_index(['numeric','都道府県名'])

In [286]:
juki_by_pref.tail()

                      総数  全人口_年齢性別判明分   0歳から4歳  ...  90歳から94歳  95歳から99歳  100歳以上
numeric 都道府県名                                   ...
44.0    大分県      1141784      1141741    40983  ...     22614      6801    1016
45.0    宮崎県      1087372      1087241    42167  ...     20825      6358    1066
46.0    鹿児島県     1617850      1617517    63756  ...     32923     10772    1723
47.0    沖縄県      1485484      1485118    78778  ...     16704      5365    1220
0.0     全国     126654244    126645025  4621243  ...   1782079    521284   80636

[5 rows x 23 columns]

# VD用

#日本ワクチン

In [121]:
#この段階で四捨五入する
age12_14 = (juki_mf['10歳から14歳']/5*3).apply(lambda x: Decimal(str(x)).quantize(Decimal('0'), rounding=ROUND_HALF_UP)).astype(int)
age10_11 = (juki_mf['10歳から14歳']/5*2).apply(lambda x: Decimal(str(x)).quantize(Decimal('0'), rounding=ROUND_HALF_UP)).astype(int)

In [319]:
vac_age_raw = pd.concat([juki_mf.loc[:,'都道府県名'],
                         #年代属性別
                         juki_mf.loc[:,'0歳から4歳':'100歳以上'].sum(axis=1).rename('全人口'),
                         (age10_11 + juki_mf.loc[:,'0歳から4歳':'5歳から9歳'].sum(axis=1)).rename('12歳未満'),
                         (age12_14 + juki_mf.loc[:,'15歳から19歳':].sum(axis=1)).rename('12歳以上'),
                         (age12_14 + juki_mf.loc[:,'15歳から19歳':'60歳から64歳'].sum(axis=1)).rename('12歳から64歳'),
                         (juki_mf.loc[:,'0歳から4歳':'60歳から64歳'].sum(axis=1)).rename('64歳以下'),
                         juki_mf.loc[:,'65歳から69歳':].sum(axis=1).rename('65歳以上'),
                         #年齢別接種用
                         #12～19歳	20代	30代	40代	50代	60～64歳	65～69歳	70代	80代	90代	100歳以上
                         (age12_14 + juki_mf.loc[:,'15歳から19歳']).rename('12歳から19歳'),
                         (juki_mf.loc[:,'20歳から24歳'] + juki_mf.loc[:,'25歳から29歳']).rename('20代'),
                         (juki_mf.loc[:,'30歳から34歳'] + juki_mf.loc[:,'35歳から39歳']).rename('30代'),
                         (juki_mf.loc[:,'40歳から44歳'] + juki_mf.loc[:,'45歳から49歳']).rename('40代'),
                         (juki_mf.loc[:,'50歳から54歳'] + juki_mf.loc[:,'55歳から59歳']).rename('50代'),
                         juki_mf.loc[:,'60歳から64歳'],
                         juki_mf.loc[:,'65歳から69歳'],
                         (juki_mf.loc[:,'70歳から74歳'] + juki_mf.loc[:,'75歳から79歳']).rename('70代'),
                         (juki_mf.loc[:,'80歳から84歳'] + juki_mf.loc[:,'85歳から89歳']).rename('80代'),
                         (juki_mf.loc[:,'90歳から94歳'] + juki_mf.loc[:,'95歳から99歳']).rename('90代'),
                         juki_mf.loc[:,'100歳以上']],axis=1).fillna(0)

In [320]:
#都道府県別
vac_age = vac_age_raw.groupby('都道府県名').sum().reindex(pref_code['都道府県名'].to_list()).astype(int)
vac_age.loc['全国'] = vac_age.sum()

In [321]:
vac_age['numeric'] = vac_age.index.map(pref_code_dic)
vac_age = vac_age.reset_index(drop=False).set_index(['numeric','都道府県名'])

In [322]:
vac_age.tail()

                     全人口     12歳未満      12歳以上  ...      80代      90代  100歳以上
numeric 都道府県名                                  ...
44.0    大分県      1141741    108597    1033144  ...    97874    29415    1016
45.0    宮崎県      1087241    112010     975231  ...    91648    27183    1066
46.0    鹿児島県     1617517    168440    1449077  ...   137509    43695    1723
47.0    沖縄県      1485118    198243    1286875  ...    82170    22069    1220
0.0     全国     126645025  12027309  114617716  ...  9058480  2303363   80636

[5 rows x 17 columns]

In [323]:
#日本ワクチンの「人口」シートを更新
set_with_dataframe(japan_vax.worksheet('人口'),vac_age,include_index=True,resize=False)

#日本BD

In [324]:
age_group_raw = pd.concat([juki_mf.loc[:,'都道府県名'],
                           juki_mf.loc[:,'0歳から4歳':].sum(axis=1).rename('全人口'),
                           (juki_mf['0歳から4歳'] + juki_mf['5歳から9歳']).rename('10歳未満'),
                           (juki_mf['10歳から14歳'] + juki_mf['15歳から19歳']).rename('10代'),
                           (juki_mf['20歳から24歳'] + juki_mf['25歳から29歳']).rename('20代'),
                           (juki_mf['30歳から34歳'] + juki_mf['35歳から39歳']).rename('30代'),
                           (juki_mf['40歳から44歳'] + juki_mf['45歳から49歳']).rename('40代'),
                           (juki_mf['50歳から54歳'] + juki_mf['55歳から59歳']).rename('50代'),
                           (juki_mf['60歳から64歳'] + juki_mf['65歳から69歳']).rename('60代'),
                           (juki_mf['70歳から74歳'] + juki_mf['75歳から79歳']).rename('70代'),
                           (juki_mf['80歳から84歳'] + juki_mf['85歳から89歳']).rename('80代'),
                           (juki_mf['90歳から94歳'] + juki_mf['95歳から99歳']).rename('90代'),
                           juki_mf.loc[:,'100歳以上'],
                           juki_mf.loc[:,'80歳から84歳':'100歳以上'].sum(axis=1).rename('80歳以上')],axis=1).fillna(0)

In [325]:
#都道府県別
age_group = age_group_raw.groupby('都道府県名').sum().reindex(pref_code['都道府県名'].to_list()).astype(int)
age_group.loc['全国'] = age_group.sum()

In [326]:
age_group['numeric'] = age_group.index.map(pref_code_dic)
age_group = age_group.reset_index(drop=False).set_index(['numeric','都道府県名'])

In [327]:
#Vdata用に順番並べ替え
age_group[age_group.columns[:-5].to_list()+['80歳以上']+age_group.columns[-5:-1].to_list()].tail()

                     全人口    10歳未満       10代  ...      80代      90代  100歳以上
numeric 都道府県名                                ...
44.0    大分県      1141741    88348    101871  ...    97874    29415    1016
45.0    宮崎県      1087241    91290    102324  ...    91648    27183    1066
46.0    鹿児島県     1617517   137810    150774  ...   137509    43695    1723
47.0    沖縄県      1485118   164287    166153  ...    82170    22069    1220
0.0     全国     126645025  9832897  11204704  ...  9058480  2303363   80636

[5 rows x 13 columns]

In [329]:
#日本BDの「人口」シートに書き込み
set_with_dataframe(japan.worksheet('人口'),age_group[age_group.columns[:-5].to_list()+['80歳以上']+age_group.columns[-5:-1].to_list()].tail(),include_index=True,resize=False)

# Vdata automation用のcsv

In [336]:
age_automation = pd.concat([juki_by_pref, vac_age.add_suffix('_VD_vac'),age_group.add_suffix('_VD_jp')],axis=1)

In [337]:
age_automation.to_csv('age_vdata.csv')

In [338]:
from google.colab import files
files.download('age_vdata.csv')

In [334]:
age_automation

                      総数  全人口_年齢性別判明分  ...  100歳以上_VD日本  80歳以上_VD日本
numeric 都道府県名                          ...
1.0     北海道      5228732      5226603  ...         3858      538009
2.0     青森県      1260067      1259615  ...          699      137683
3.0     岩手県      1221205      1220823  ...          916      144071
4.0     宮城県      2282106      2281989  ...         1358      206520
5.0     秋田県       971604       971288  ...          767      130319
6.0     山形県      1070017      1069562  ...          880      129045
7.0     福島県      1862777      1862059  ...         1333      194191
8.0     茨城県      2907678      2907675  ...         1616      252862
9.0     栃木県      1955402      1955401  ...         1054      166772
10.0    群馬県      1958185      1958101  ...         1332      181494
11.0    埼玉県      7393849      7393799  ...         2929      557258
12.0    千葉県      6322897      6322892  ...         2872      507013
13.0    東京都     13843525     13843329  ...         6641     1023568
14.0    神奈川県     9220245      9220206  ...         4315      718031
15.0    新潟県      2213353      2213174  ...         2068      246879
16.0    富山県      1047713      1047674  ...          873      110371
17.0    石川県      1132656      1132656  ...          915      105315
18.0    福井県       774596       774583  ...          622       78151
19.0    山梨県       821094       820997  ...          789       84329
20.0    長野県      2072219      2071737  ...         2039      231094
21.0    岐阜県      2016868      2016791  ...         1308      194288
22.0    静岡県      3686335      3686260  ...         2448      350171
23.0    愛知県      7558872      7558802  ...         3190      573444
24.0    三重県      1800756      1800557  ...         1155      174481
25.0    滋賀県      1418886      1418843  ...          850      113491
26.0    京都府      2530609      2530542  ...         1885      237048
27.0    大阪府      8839532      8839511  ...         4166      740007
28.0    兵庫県      5523627      5523625  ...         3308      497964
29.0    奈良県      1344952      1344739  ...          917      131398
30.0    和歌山県      944750       944432  ...          786      104505
31.0    鳥取県       556959       556788  ...          611       62116
32.0    島根県       672979       672815  ...          866       84100
33.0    岡山県      1893874      1893791  ...         1618      190608
34.0    広島県      2812477      2812433  ...         2362      264311
35.0    山口県      1356144      1356110  ...         1381      157367
36.0    徳島県       735070       734949  ...          591       82269
37.0    香川県       973922       973896  ...          909      100494
38.0    愛媛県      1356343      1356219  ...         1280      150550
39.0    高知県       701531       701167  ...          840       86627
40.0    福岡県      5124259      5124170  ...         3492      443665
41.0    佐賀県       818251       818222  ...          705       82812
42.0    長崎県      1336023      1335938  ...         1280      148793
43.0    熊本県      1758815      1758645  ...         1787      192407
44.0    大分県      1141784      1141741  ...         1016      128305
45.0    宮崎県      1087372      1087241  ...         1066      119897
46.0    鹿児島県     1617850      1617517  ...         1723      182927
47.0    沖縄県      1485484      1485118  ...         1220      105459
0.0     全国     126654244    126645025  ...        80636    11442479

[48 rows x 53 columns]