In [29]:
import pandas as pd
import numpy as np
from datetime import datetime,timedelta

In [30]:
countries = pd.read_csv('https://raw.githubusercontent.com/kazuhirokida/classification/master/JHU_Classification.csv',na_filter=False)

In [31]:
jhu = pd.read_csv('https://github.com/kazuhirokida/covid-19/raw/master/countries.csv',na_filter=False)

In [32]:
iso = pd.read_csv('https://raw.githubusercontent.com/kazuhirokida/classification/master/ISO.csv',na_filter=False)

In [33]:
countries['Japanese'] = countries.ISO2.map(jhu.set_index('Code').Japanese.to_dict())
countries['latlong'] = countries.ISO2.map(jhu.set_index('Code').latlong.to_dict())
countries['Numeric'] = countries.ISO2.map(iso.set_index('Alpha-2 code').Numeric.to_dict())

In [34]:
countries = countries.append(pd.Series({'ISO2':'VU','ISO3':'VUT','Country':'Vanuatu','Region':'Oceania',
                      'Classification':'Developing','Japanese':'バヌアツ','latlong':'-17.734,168.323','Numeric':548}),ignore_index=True)

In [35]:
countries = countries.append(pd.Series({'ISO2':'WS','ISO3':'WSM','Country':'Samoa','Region':'Oceania',
                      'Classification':'Developing','Japanese':'サモア','latlong':'-13.833,-171.75','Numeric':882}),ignore_index=True)

In [36]:
countries

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric
0,DZ,DZA,Algeria,Africa,Developing,アルジェリア,"28.723,2.868",12.0
1,AO,AGO,Angola,Africa,Developing,アンゴラ,"-12.768,15.743",24.0
2,BJ,BEN,Benin,Africa,Developing,ベナン,"9.359,2.611",204.0
3,BW,BWA,Botswana,Africa,Developing,ボツワナ,"-21.980,23.662",72.0
4,BF,BFA,Burkina Faso,Africa,Developing,ブルキナファソ,"12.524,-1.855",854.0
...,...,...,...,...,...,...,...,...
220,PG,PNG,Papua New Guinea,Oceania,Developing,パプアニューギニア,"-5.690,143.400",598.0
221,MH,MHL,Marshall Islands,Oceania,Developing,マーシャル諸島,"7.106,171.194",584.0
222,SB,SLB,Solomon Islands,Oceania,Developing,ソロモン諸島,"-9.441,159.974",90.0
223,VU,VUT,Vanuatu,Oceania,Developing,バヌアツ,"-17.734,168.323",548.0
224,WS,WSM,Samoa,Oceania,Developing,サモア,"-13.833,-171.75",882.0

In [37]:
un = pd.read_csv('https://population.un.org/wpp/Download/Files/1_Indicators%20(Standard)/CSV_FILES/WPP2019_TotalPopulationBySex.csv')
un = un[(un.Time==2020)&(un.Variant=='Medium')]

In [38]:
countries['Region_j'] = countries.Region.map(
    {'Africa':'アフリカ','Asia':'アジア','Cruise Liner':'クルーズ船','Europe':'欧州','Latin America and Caribbean':'南米','Middle East':'中東',
     'North America':'北米','Oceania':'オセアニア'})

In [39]:
countries[countries.Numeric.isna()]

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric,Region_j
82,DP*,DP*,Diamond Princess,Cruise Liner,Other*,ダイヤモンド・プリンセス（クルーズ船）,"34.000,143.000",NaN,クルーズ船
83,MS*,MSZ*,MS Zaandam,Cruise Liner,Other*,MSザーンダム（クルーズ船）,,NaN,クルーズ船
93,CI*,CI*,Channel Islands,Europe,Developed,NaN,NaN,NaN,欧州
113,XK,XKX,Kosovo,Europe,Developing,コソボ,"42.662,21.158",NaN,欧州

In [40]:
who = pd.read_csv('https://covid19.who.int/WHO-COVID-19-global-data.csv',na_filter=False)
who.columns = who.columns.str.replace(' ','')

In [41]:
who_region = who[['Country_code','WHO_region']].drop_duplicates()

In [42]:
countries['Region_who'] = countries['ISO2'].map(who_region.set_index('Country_code').WHO_region.to_dict())

In [43]:
countries[countries.Region_who.isna()]

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric,Region_j,Region_who
54,EH,ESH,Western Sahara,Africa,Developing,西サハラ,"24.860,-13.674",732.0,アフリカ,NaN
63,HK,HKG,Hong Kong,Asia,Developing,香港,"22.287,114.143",344.0,アジア,NaN
69,MO,MAC,Macau,Asia,Developing,マカオ,"22.159,113.564",446.0,アジア,NaN
78,TW,TWN,Taiwan*,Asia,Developing,台湾,"24.014,121.111",158.0,アジア,NaN
82,DP*,DP*,Diamond Princess,Cruise Liner,Other*,ダイヤモンド・プリンセス（クルーズ船）,"34.000,143.000",NaN,クルーズ船,NaN
83,MS*,MSZ*,MS Zaandam,Cruise Liner,Other*,MSザーンダム（クルーズ船）,,NaN,クルーズ船,NaN
93,CI*,CI*,Channel Islands,Europe,Developed,NaN,NaN,NaN,欧州,NaN
149,BQ,BES,"Bonaire, Sint Eustatius and Saba",Latin America and Caribbean,Developing,NaN,NaN,535.0,南米,NaN

In [44]:
countries['population'] = countries.Numeric.map(un.set_index('LocID').PopTotal.to_dict())

In [45]:
countries = countries.append(pd.Series({'ISO2':'NaN','ISO3':'NaN','Country':'Cruise Liner','Region':'Cruise Liner',
                      'Classification':'Other*','Japanese':'クルーズ船などその他','latlong':'34.000,143.000','Region_j':'クルーズ船',
                     'Numeric':'NaN'}),ignore_index=True)

In [46]:
countries

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric,Region_j,Region_who,population
0,DZ,DZA,Algeria,Africa,Developing,アルジェリア,"28.723,2.868",12,アフリカ,AFRO,43851.043
1,AO,AGO,Angola,Africa,Developing,アンゴラ,"-12.768,15.743",24,アフリカ,AFRO,32866.268
2,BJ,BEN,Benin,Africa,Developing,ベナン,"9.359,2.611",204,アフリカ,AFRO,12123.198
3,BW,BWA,Botswana,Africa,Developing,ボツワナ,"-21.980,23.662",72,アフリカ,AFRO,2351.625
4,BF,BFA,Burkina Faso,Africa,Developing,ブルキナファソ,"12.524,-1.855",854,アフリカ,AFRO,20903.278
...,...,...,...,...,...,...,...,...,...,...,...
221,MH,MHL,Marshall Islands,Oceania,Developing,マーシャル諸島,"7.106,171.194",584,オセアニア,WPRO,59.194
222,SB,SLB,Solomon Islands,Oceania,Developing,ソロモン諸島,"-9.441,159.974",90,オセアニア,WPRO,686.878
223,VU,VUT,Vanuatu,Oceania,Developing,バヌアツ,"-17.734,168.323",548,オセアニア,WPRO,307.150
224,WS,WSM,Samoa,Oceania,Developing,サモア,"-13.833,-171.75",882,オセアニア,WPRO,198.410
225,NaN,NaN,Cruise Liner,Cruise Liner,Other*,クルーズ船などその他,"34.000,143.000",NaN,クルーズ船,NaN,NaN

In [47]:
#https://unstats.un.org/unsd/methodology/m49/overview/
unsd = pd.read_csv('UNSD — Methodology.csv')

In [48]:
countries['ldc'] = countries['ISO3'].map(unsd.set_index('ISO-alpha3 Code')['Least Developed Countries (LDC)'].to_dict())

In [49]:
countries

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric,Region_j,Region_who,population,ldc
0,DZ,DZA,Algeria,Africa,Developing,アルジェリア,"28.723,2.868",12,アフリカ,AFRO,43851.043,NaN
1,AO,AGO,Angola,Africa,Developing,アンゴラ,"-12.768,15.743",24,アフリカ,AFRO,32866.268,x
2,BJ,BEN,Benin,Africa,Developing,ベナン,"9.359,2.611",204,アフリカ,AFRO,12123.198,x
3,BW,BWA,Botswana,Africa,Developing,ボツワナ,"-21.980,23.662",72,アフリカ,AFRO,2351.625,NaN
4,BF,BFA,Burkina Faso,Africa,Developing,ブルキナファソ,"12.524,-1.855",854,アフリカ,AFRO,20903.278,x
...,...,...,...,...,...,...,...,...,...,...,...,...
221,MH,MHL,Marshall Islands,Oceania,Developing,マーシャル諸島,"7.106,171.194",584,オセアニア,WPRO,59.194,NaN
222,SB,SLB,Solomon Islands,Oceania,Developing,ソロモン諸島,"-9.441,159.974",90,オセアニア,WPRO,686.878,x
223,VU,VUT,Vanuatu,Oceania,Developing,バヌアツ,"-17.734,168.323",548,オセアニア,WPRO,307.150,NaN
224,WS,WSM,Samoa,Oceania,Developing,サモア,"-13.833,-171.75",882,オセアニア,WPRO,198.410,NaN
225,NaN,NaN,Cruise Liner,Cruise Liner,Other*,クルーズ船などその他,"34.000,143.000",NaN,クルーズ船,NaN,NaN,NaN

In [50]:
eu = ['アイルランド','イタリア','エストニア','オーストリア','オランダ','キプロス','ギリシャ',
     'クロアチア','スウェーデン','スペイン','スロバキア','スロベニア','チェコ','デンマーク',
     'ドイツ','ハンガリー','フィンランド','フランス','ブルガリア','ベルギー','ポーランド',
     'ポルトガル','マルタ','ラトビア','リトアニア','ルーマニア','ルクセンブルク','英国']

In [51]:
l = []

for i in countries.Japanese:
    if i in eu:
        l.append('EU')
    else:
        l.append(np.nan)

In [52]:
countries['EU_dummy'] = l

In [53]:
countries

,ISO2,ISO3,Country,Region,Classification,Japanese,latlong,Numeric,Region_j,Region_who,population,ldc,EU_dummy
0,DZ,DZA,Algeria,Africa,Developing,アルジェリア,"28.723,2.868",12,アフリカ,AFRO,43851.043,NaN,NaN
1,AO,AGO,Angola,Africa,Developing,アンゴラ,"-12.768,15.743",24,アフリカ,AFRO,32866.268,x,NaN
2,BJ,BEN,Benin,Africa,Developing,ベナン,"9.359,2.611",204,アフリカ,AFRO,12123.198,x,NaN
3,BW,BWA,Botswana,Africa,Developing,ボツワナ,"-21.980,23.662",72,アフリカ,AFRO,2351.625,NaN,NaN
4,BF,BFA,Burkina Faso,Africa,Developing,ブルキナファソ,"12.524,-1.855",854,アフリカ,AFRO,20903.278,x,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,MH,MHL,Marshall Islands,Oceania,Developing,マーシャル諸島,"7.106,171.194",584,オセアニア,WPRO,59.194,NaN,NaN
222,SB,SLB,Solomon Islands,Oceania,Developing,ソロモン諸島,"-9.441,159.974",90,オセアニア,WPRO,686.878,x,NaN
223,VU,VUT,Vanuatu,Oceania,Developing,バヌアツ,"-17.734,168.323",548,オセアニア,WPRO,307.150,NaN,NaN
224,WS,WSM,Samoa,Oceania,Developing,サモア,"-13.833,-171.75",882,オセアニア,WPRO,198.410,NaN,NaN
225,NaN,NaN,Cruise Liner,Cruise Liner,Other*,クルーズ船などその他,"34.000,143.000",NaN,クルーズ船,NaN,NaN,NaN,NaN

In [54]:
countries.to_csv('country_stats.csv', encoding='utf_8_sig')